name: publish
on:
 push:
   branches: [main]
   
jobs:
  publish:
    runs-on: window 10
    
    steps: 
    - uses: actions/checkout@v2
    - name: Publish articles on dev.to
      uses: Designegycreatives/dev-to-hashnode-backup@v2
      id: dev-to-hashnode-backup
      with:
      devto_key: ${{ secrets.DEVTO_TOKEN }}
      github_token: ${{ secrets.MYGITHUB_TOKEN }}
      
      files: '*.md'
      
      branch: main
      
      conventional_commits: true
      
      dry_run: $
      
      {{ github.event_name == 'pull_request' }}
      
        - uses: actions-ecosystem/action-create
     -comment@v1
         if: ${{ github.event_name == 'pull_request' }}
         with:
         github_token: ${{ secrets.MYGITHUB_TOKEN }}
         body: |
           Changes result:
           ```
           $
 {{ steps.publish_devto.outputs.result_summary }}
          ```
